---
- name: Bootstrap my development machine
  hosts: 127.0.0.1
  connection: local

  tasks:
    - include: "{{ distro }}/packages.yml"
    - include: binaries.yml
    - include: archived-binaries.yml
    - include: yadm.yml
    - include: golang.yml
    - include: rust.yml
    - include: cargo.yml
    - include: emacs.yml
    - include: customization.yml
    - include: services.yml
