dotfiles:
  repo:
    url: https://github.com/syvanpera/dotfiles.git
    branch: devbox

apt_repositories:
  - ppa:neovim-ppa/unstable

packages:
  - bat
  - curl
  - direnv
  - eza
  - gcc
  - golang
  - neovim
  - nodejs
  - npm
  - unzip
  - ripgrep
  - stow
  - tig
  - tmux
