dotfiles:
  repo:
    url: https://github.com/syvanpera/dotfiles.git
    branch: devbox

# apt_repositories:
#   - ppa:neovim-ppa/unstable

packages:
  - bat
  - curl
  - direnv
  - eza
  - file
  - gcc
  - golang
  - gnupg
  - jq
  # - neovim
  # - nodejs
  # - npm
  - pass
  - python3
  - python3-venv
  - unzip
  - ripgrep
  - rng-tools
  - stow
  - tig
  - tmux
  - zsh

rust_packages:
  - fd-find
  - git-delta
  - procs
  - yazi-fm
  - yazi-cli
