dotfiles:
  repo:
    url: https://github.com/syvanpera/dotfiles.git
    branch: devbox

apt_repositories:
  - ppa:neovim-ppa/unstable

packages:
  - bat
  - direnv
  - eza
  - neovim
  - ripgrep
  - stow
  - tig
  - tmux
