- name: Install GUI packages
  become: yes
  package:
    state: present
    name: "{{ gui_packages }}"

- name: Write udevmon config
  become: yes
  copy:
    dest: "/etc/interception/udevmon.yaml"
    content: |
      - JOB: interception -g $DEVNODE | caps2esc -m 1 | uinput -d $DEVNODE
        DEVICE:
          EVENTS:
            EV_KEY: [KEY_CAPSLOCK, KEY_ESC]

- name: Reload udevmon service
  become: yes
  ansible.builtin.systemd_service:
    name: udevmon.service
    state: reloaded

- include_tasks: "fonts.yml"

